apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: run-migrations
          image: ghcr.io/vianaz/stone-sre-devops-challenge
          command: ["pnpm", "migration:run", "--force"]
          envFrom:
            - configMapRef:
                name: api-config
      containers:
        - name: api
          image: ghcr.io/vianaz/stone-sre-devops-challenge
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: http
              path: /health
            initialDelaySeconds: 15
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: api-config
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - name: http
              containerPort: 8080
