apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
