apiVersion: v1
kind: Service
metadata:
  name: api
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "${LOAD_BALANCER_ID}"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "${LOAD_BALANCER_SIZE_UNIT}"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  selector:
    app: api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
