services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    environment:
      - TZ=UTC
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=debug
      - APP_KEY=H5TfJkzRDwDw_Hj5-FRu6hZJRXszYT8J
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=stone-sre-devops-challange-password
      - DB_DATABASE=postgres

  postgres:
    image: postgres:16
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: stone-sre-devops-challange-password


volumes:
  db_data:
