apiVersion: v1
kind: Service
metadata:
  name: postgres
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432