apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  {{- with .Values.env }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
  {{- end -}}
