name: CI Pipeline

on:
  pull_request:
    branches:
      - main
env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: 20.11.1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: "lint-results.json"
          check-name: "lint"
          fail-on-warning: false
          fail-on-error: true

  build:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      image_name_with_tag: ${{ steps.meta.outputs.tags }}
      artifact_name: ${{ env.ARTIFACT_NAME }}
    env:
      DOCKER_FILE: .devops/docker/Dockerfile
      ARTIFACT_NAME: stone-sre-devops-challenge-${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and export
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

          outputs: type=docker,dest=/tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp/${{ env.ARTIFACT_NAME }}.tar
          retention-days: 3

  tests:
    runs-on: ubuntu-latest
    needs: [build, lint]
    env:
      TZ: UTC
      PORT: 3000
      HOST: 0.0.0.0
      LOG_LEVEL: debug
      NODE_ENV: test
      APP_KEY: H5TfJkzRDwDw_Hj5-FRu6hZJRXszYT8J
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: stone-sre-devops-challange-password
      DB_DATABASE: postgres
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

  image-scan:
    runs-on: ubuntu-latest
    needs: [build, lint, tests]
    env:
      ARTIFACT_NAME: ${{ needs.build.outputs.artifact_name }}
      IMAGE_NAME_WITH_TAG: ${{ needs.build.outputs.image_name_with_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME_WITH_TAG }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-docker.sarif'
          severity: 'CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-docker.sarif'

  # push-and-sign-image:
  #   runs-on: ubuntu-latest
  #   needs: [image-scan, build, lint, tests]
  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write
  #     attestations: write
  #   env:
  #     ARTIFACT_NAME: ${{ needs.build.outputs.artifact_name }}
  #     IMAGE_NAME_WITH_TAG: ${{ needs.build.outputs.image_name_with_tag }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ env.DOCKER_REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Download artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: ${{ env.ARTIFACT_NAME }}
  #         path: /tmp

  #     - name: Load image
  #       run: |
  #         docker load --input /tmp/${{ env.ARTIFACT_NAME }}.tar

  #     - name: Push image to GitHub Container Registry
  #       id: push
  #       run: |
  #         docker push ${{ env.IMAGE_NAME_WITH_TAG }}
  #         digest=$(docker image inspect ghcr.io/vianaz/stone-sre-devops-challenge:main --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)
  #         echo "digest=$digest" >> "$GITHUB_OUTPUT"

  #     - name: Attest
  #       uses: actions/attest-build-provenance@v1.4.3
  #       id: attest
  #       with:
  #         subject-name: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
  #         subject-digest: ${{ steps.push.outputs.digest }}
  #         push-to-registry: true

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [push-and-sign-image, build]
  #   environment: production
  #   permissions:
  #     id-token: write
  #     contents: read
  #     actions: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: digitalocean/action-doctl@v2
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  #     - name: Save DigitalOcean kubeconfig
  #       run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.K8S_CLUSTER_ID }}

  #     - name: Install Helm chart
  #       uses: WyriHaximus/github-action-helm3@v3
  #       with:
  #         exec: |
  #           helm upgrade stone-sre-devops-challenge .devops/helm --install --set container.tag=main --set container.pullPolicy=Always --set env.DB_PASSWORD=${{ secrets.DB_PASSWORD }} --set env.DB_DATABASE=${{ secrets.DB_USER }} --set env.DB_USER=${{ secrets.DB_USER }} --set env.DB_PORT=${{ vars.DB_PORT }} --set env.DB_HOST=${{ vars.DB_HOST }} --set env.NODE_ENV="production" --set env.APP_KEY=${{ secrets.APP_KEY }} --set env.LOG_LEVEL="debug"


