name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  build:
    needs: lint
    uses: ./.github/workflows/build.yaml

  tests:
    needs: [build, lint]
    uses: ./.github/workflows/tests.yaml

  image-scan:
    uses: ./.github/workflows/scan.yaml
    needs: [build, lint, tests]
    with:
      artifact_name: ${{ needs.build.outputs.artifact_name }}
      image_name_with_tag: ${{ needs.build.outputs.image_name_with_tag }}
      post-scan-action: ${{ github.ref == 'refs/heads/main' }}
