# name: CI Pull Request

# on:
#   pull_request:

# jobs:
#   comment-approval:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Comment on Issue
#         uses: peter-evans/create-or-update-comment@v1
#         with:
#           issue-number: ${{ github.event.number }}
#           body: |
#             ### :green_circle: Deploy Preview :green_circle:

#             **Ready for deployment**: React to this comment with :rocket: to deploy the preview.
