name: CI/CD Pull Request

on:
  issue_comment:
    types:
      - created

jobs:
  deploy-approval:
    if: github.event_name == 'issue_comment' && github.event.comment.reactions == 'rocket'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          edit-mode: replace
          comment-id: ${{ github.event.comment.id }}
          body: |
            ### :rocket: Deploy Preview :rocket:

            Deploy aproved by: ${{ github.actor }}
            **Deployment in progress...**
