name: Lint Code

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      # - uses: pnpm/action-setup@v4
      #   name: Install pnpm
      #   with:
      #     version: 9.1.4
      #     run_install: false

      # - name: Install Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: "pnpm"

      # - name: Install dependencies
      #   run: pnpm install

      - uses: ./.github/setup-pnpm/action.yaml
        with:
          version: 9.1.4
          run_install: false


      - name: Lint code
        run: pnpm lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: "lint-results.json"
          check-name: "lint"
          fail-on-warning: false
          fail-on-error: true
