name: Push and Sign Image

on:
  workflow_call:
    inputs:
      image_name_with_tag:
        required: true
        description: "The name of the image to push"
        type: string
      artifact_name:
        required: true
        description: "The name of the artifact to download"
        type: string
      docker_registry:
        required: true
        description: "The Docker registry to push the image to"
        type: string
      image_name:
        required: true
        description: "The name of the Docker image"
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      ARTIFACT_NAME: ${{ inputs.artifact_name}}
      IMAGE_NAME_WITH_TAG: ${{ inputs.image_name_with_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ inputs.artifact_name }}.tar

      - name: Push image to GitHub Container Registry
        id: push
        run: |
          docker push ${{ inputs.image_name_with_tag }}
          digest=$(docker image inspect ghcr.io/vianaz/stone-sre-devops-challenge:main --format '{{index .RepoDigests 0}}' | cut -d'@' -f2)
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

  # sign:
  #   runs-on: ubuntu-latest
  #   needs: push
  #   permissions:
  #     contents: read
  #     packages: write
  #     id-token: write
  #     attestations: write
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Attest
  #       uses: actions/attest-build-provenance@v1.4.3
  #       id: attest
  #       with:
  #         subject-name: ${{ inputs.docker_registry }}/${{ inputs.image_name }}
  #         subject-digest: ${{ needs.push.outputs.digest }}
  #         push-to-registry: true

