name: Image Scan

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
        description: "The name of the artifact to download"
      image_name_with_tag:
        required: true
        type: string
        description: "The name of the image to scan"
      post-scan-action:
        required: true
        type: boolean
        description: "The action to run after the scan"

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: ${{ inputs.artifact_name }}
      IMAGE_NAME_WITH_TAG: ${{ inputs.image_name_with_tag }}
      TRIVY_FILENAME: trivy-results.sarif

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        continue-on-error: true
        with:
          image-ref: ${{ env.IMAGE_NAME_WITH_TAG }}
          format: "sarif"
          output: ${{ env.TRIVY_FILENAME }}
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true

      - name: Post SARIF findings in the pull request
        if: github.event_name == 'pull_request'
        uses: sett-and-hive/sarif-to-comment-action@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          pr-number: ${{ github.event.number }}
          sarif-file: ${{ env.TRIVY_FILENAME }}
          title: Security scan results
          dry-run: false

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ inputs.post-scan-action }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.TRIVY_FILENAME }}
