name: Image Scan

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
        description: "The name of the artifact to download"
      image_name_with_tag:
        required: true
        type: string
        description: "The name of the image to scan"

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: ${{ inputs.artifact_name }}
      IMAGE_NAME_WITH_TAG: ${{ inputs.image_name_with_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/${{ env.ARTIFACT_NAME }}.tar

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        continue-on-error: true
        with:
          image-ref: ${{ env.IMAGE_NAME_WITH_TAG }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
